name = "BeamLib"
uuid = "5cc2bb23-e00d-472a-be50-43f5352c66b1"
authors = ["Matthias Schön"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAngles = "6fb2a4bd-7999-5318-a3b2-8ad61056cd98"

[compat]
LinearAlgebra = "1.11.0"
PhysicalConstants = "0.2.3"
Unitful = "1.21.0"
UnitfulAngles = "0.7.2"
