name = "BeamLib"
uuid = "5cc2bb23-e00d-472a-be50-43f5352c66b1"
authors = ["Matthias Schön"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
